# Spring Application Name
spring.application.name=spotgo-backend

# App Port
server.port=8080

# Spring DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/spotgo-db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true

#Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Application Information for Documentation

# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# Seeder: set to true to wipe tables before inserting seed data
app.seeder.reset-before-seed=true

# i18n Message Bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8
