package com.axiora.spotgo.monitoring.interfaces.rest.resources;

import io.swagger.v3.oas.annotations.media.Schema;

public record SpotUtilizationResource(
        @Schema(description = "Unique identifier of the analytics row", example = "su-1")
        String id,
        @Schema(description = "Spot identifier", example = "A1")
        String spotId,
        @Schema(description = "Spot display name", example = "A1")
        String spotName,
        @Schema(description = "Zone label", example = "Level A")
        String zone,
        @Schema(description = "Spot type", example = "standard")
        String type,
        @Schema(description = "Spot status", example = "occupied")
        String status,
        @Schema(description = "Number of reservations for the selected period", example = "12")
        Integer dailyTurnover,
        @Schema(description = "Relative utilization versus top spot, in percent", example = "87")
        Integer peakUtilization,
        @Schema(description = "Revenue generated by this spot for the selected period", example = "96.0")
        Double revenueImpact
) {}
